<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23016" started-at="2022-01-14T19:28:28 IST" finished-at="2022-01-14T19:28:51 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23016" started-at="2022-01-14T19:28:28 IST" finished-at="2022-01-14T19:28:51 IST">
      <class name="Test.LoginTest">
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:Test.LoginTest@d6da883]" name="OpenBrowser" is-config="true" duration-ms="12121" started-at="2022-01-14T19:28:28 IST" finished-at="2022-01-14T19:28:40 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="FAIL" signature="loginToZerodhaWithCredetials()[pri:0, instance:Test.LoginTest@d6da883]" name="loginToZerodhaWithCredetials" duration-ms="1024" started-at="2022-01-14T19:28:40 IST" finished-at="2022-01-14T19:28:41 IST">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method Test.LoginTest.loginToZerodhaWithCredetials() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Test.LoginTest.loginToZerodhaWithCredetials() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToZerodhaWithCredetials -->
        <test-method status="PASS" signature="screenshot(org.testng.ITestResult)[pri:0, instance:Test.LoginTest@d6da883]" name="screenshot" is-config="true" duration-ms="249" started-at="2022-01-14T19:28:41 IST" finished-at="2022-01-14T19:28:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToZerodhaWithCredetials status=FAILURE method=LoginTest.loginToZerodhaWithCredetials()[pri:0, instance:Test.LoginTest@d6da883] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshot -->
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:Test.LoginTest@d6da883]" name="OpenBrowser" is-config="true" duration-ms="5444" started-at="2022-01-14T19:28:41 IST" finished-at="2022-01-14T19:28:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="loginToZerodhaWithVaildCredetials()[pri:0, instance:Test.LoginTest@d6da883]" name="loginToZerodhaWithVaildCredetials" duration-ms="3986" started-at="2022-01-14T19:28:47 IST" finished-at="2022-01-14T19:28:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToZerodhaWithVaildCredetials -->
        <test-method status="PASS" signature="screenshot(org.testng.ITestResult)[pri:0, instance:Test.LoginTest@d6da883]" name="screenshot" is-config="true" duration-ms="1" started-at="2022-01-14T19:28:51 IST" finished-at="2022-01-14T19:28:51 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginToZerodhaWithVaildCredetials status=SUCCESS method=LoginTest.loginToZerodhaWithVaildCredetials()[pri:0, instance:Test.LoginTest@d6da883] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshot -->
        <test-method status="SKIP" signature="login()[pri:0, instance:Test.LoginTest@d6da883]" name="login" duration-ms="0" started-at="2022-01-14T19:28:51 IST" depends-on-methods="Test.LoginTest.loginToZerodhaWithCredetials" finished-at="2022-01-14T19:28:51 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.login()[pri:0, instance:Test.LoginTest@d6da883] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.login()[pri:0, instance:Test.LoginTest@d6da883] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- Test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
